AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DE-Extract
  VpcCIDR:
    Description: The IP range for this VPC
    Type: String
    Default: 192.168.0.0/16
  DataCenterPublicSubnetCIDR:
    Description: The IP range  for the public subnet
    Type: String
    Default: 192.168.10.0/24
Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
          CidrBlock: 192.168.0.0/16
          EnableDnsSupport: true
          EnableDnsHostnames: true
          Tags:
          - Key: Name
            Value: !Ref EnvironmentName
    InternetGateway:
      Type: AWS::EC2::InternetGateway
    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          InternetGatewayId: !Ref InternetGateway
          VpcId: !Ref VPC       
    DataCenterPublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
          AvailabilityZone: !Select [ 0, !GetAZs '' ]
          CidrBlock: !Ref DataCenterPublicSubnetCIDR
          MapPublicIpOnLaunch: true
          Tags:
            - Key: Name
              Value: DE-Extract Data Center Subnet
          VpcId: !Ref VPC      
    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
          Tags:
            - Key: Name
              Value: DE-Extract Public Routes
          VpcId: !Ref VPC 
    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
          RouteTableId: !Ref PublicRouteTable
          DestinationCidrBlock: 0.0.0.0/0
          GatewayId: !Ref InternetGateway            
    DataCenterPublicSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId: !Ref PublicRouteTable
          SubnetId: !Ref DataCenterPublicSubnet 
    WindowsInstanceSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "DE-Extract-WindowsInstanceSG"
        GroupDescription: Security group for remote access
        SecurityGroupIngress:
          - IpProtocol: tcp
            CidrIp: 0.0.0.0/0
            FromPort: 3389
            ToPort: 3389
        VpcId: !Ref VPC
        Tags:
          - Key: Name
            Value: DE-Extract-WindowsInstanceSG
    FileServerSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupName: "DE-Extract-FileServerSG"
          GroupDescription: Security group for SSH access
          SecurityGroupIngress:
            - IpProtocol: tcp
              CidrIp: 192.168.10.0/24
              FromPort: 22
              ToPort: 22
          VpcId: !Ref VPC
          Tags:
            - Key: Name
              Value: DE-Extract-FileServerSG
    FileGatewaySG:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupName: "DE-Extract-FileGatewaySG"
          GroupDescription: Security group for File gateway access
          SecurityGroupIngress:
            - IpProtocol: tcp
              CidrIp: 192.168.0.0/16
              FromPort: 1
              ToPort: 65534
          VpcId: !Ref VPC
          Tags:
            - Key: Name
              Value: DE-Extract-FileGatewaySG          